namespace System;

public interface IOutput {
    void Write(ulong value);
    void Write(uint value);
    void Write(StringBuilder? value);
    void Write(string format, params object?[] arg);
    void Write(string format, object? arg0, object? arg1, object? arg2);
    void Write(string format, object? arg0, object? arg1);
    void Write(string format, object? arg0);
    void Write(string? value);
    void Write(object? value);
    void Write(long value);
    void Write(int value);
    void Write(double value);
    void Write(decimal value);
    void Write(char[] buffer, int index, int count);
    void Write(char[]? buffer);
    void Write(char value);
    void Write(bool value);
    void Write(float value);
    void WriteLine(ulong value);
    void WriteLine(uint value);
    void WriteLine(StringBuilder? value);
    void WriteLine(string format, params object?[] arg);
    void WriteLine(string format, object? arg0);
    void WriteLine(string format, object? arg0, object? arg1);
    void WriteLine(string format, object? arg0, object? arg1, object? arg2);
    void WriteLine(string? value);
    void WriteLine(float value);
    void WriteLine(object? value);
    void WriteLine(bool value);
    void WriteLine(char value);
    void WriteLine(char[]? buffer);
    void WriteLine();
    void WriteLine(decimal value);
    void WriteLine(double value);
    void WriteLine(int value);
    void WriteLine(long value);
    void WriteLine(char[] buffer, int index, int count);
}
